### PR TITLE
Updated to winapi 3.6.0

### PR DESCRIPTION
**Pull request by Tacklebox**
This should address issue #28

### CODE REVIEW

**Comment by bbigras** [comment]
Any ETA for this?

**Comment by Tacklebox** [comment]
@bbigras I think qdot is done with this project if i understand #25 correctly. If I get time I might fork to keep it going since I'm using it myself but I don't know yet.

**Comment by qdot** [comment]
@Tacklebox @bbigras Yeah I'm pretty much out on this project now, I don't have time to support it anymore. If someone wants to fork and take over, let me know. I can also turn it into an org managed repo.

**Comment by qdot** [comment]
BTW, if bringing in this patch will help, I can do that at least. However, I'm gonna be doing it blind, so I'll need some reassurance. :)

**Comment by udoprog** [comment]
I've got a branch where I've done a number of changes which helps writing applications with systray-rs:
https://github.com/udoprog/systray-rs

Some of the things I did:
* Moved to 2018 edition.
* Incorporated all changes from this PR.
* Callbacks are now `FnMut -> Result<(), systray::Error>` and marked them `Send + Sync`.
  * Without `FnMut`, you can take mutable ownership of things from the closure's environment which really limits utility.
* Renamed error type from `SystrayError` to `Error` and added a variant which takes a boxed error from the callbacks.
* `&String` parameters to `&str`.
* Expose `set_icon_from_buffer` on Windows.

**Comment by qdot** [comment]
@udoprog Hey! Would you be interested in PR'ing your changes to this repo? I'm back to being active in rust again and would like to get this library upgraded, and don't wanna redo work. :)

**Comment by qdot** [comment]
I've got go-ahead from @udoprog to bring their changes into the depo. I'll do this on the dev branch and probably close out this PR when that happens.

**Comment by qdot** [comment]
As of 0.4.0, I've pulled in all of @udoprog's patches, so we're on WinAPI 0.3.8 now. I did a quick check and the example compiled and seemed to basically work on windows (had some icon issues but eh), so I'm calling this good for now.

**Pull request closed without merging**
